import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata: Metadata = {
  title: "DevChrisVaz",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default function LocaleLayout({
  children,
  params: {
    locale
  }
}: Readonly<LocaleLayoutProps>) {
  const messages = useMessages();
  return (
    <html lang={locale} className="dark">
      <body className={inter.className + " bg-gray-950"}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
